// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vnfd.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vdu struct {
	Vcpus                string   `protobuf:"bytes,1,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	Memory               string   `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	DiskSize             string   `protobuf:"bytes,3,opt,name=disk_size,json=diskSize,proto3" json:"disk_size,omitempty"`
	Image                string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Vnfcs                []*Vnfc  `protobuf:"bytes,6,rep,name=vnfcs,proto3" json:"vnfcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vdu) Reset()         { *m = Vdu{} }
func (m *Vdu) String() string { return proto.CompactTextString(m) }
func (*Vdu) ProtoMessage()    {}
func (*Vdu) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{0}
}

func (m *Vdu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vdu.Unmarshal(m, b)
}
func (m *Vdu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vdu.Marshal(b, m, deterministic)
}
func (m *Vdu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vdu.Merge(m, src)
}
func (m *Vdu) XXX_Size() int {
	return xxx_messageInfo_Vdu.Size(m)
}
func (m *Vdu) XXX_DiscardUnknown() {
	xxx_messageInfo_Vdu.DiscardUnknown(m)
}

var xxx_messageInfo_Vdu proto.InternalMessageInfo

func (m *Vdu) GetVcpus() string {
	if m != nil {
		return m.Vcpus
	}
	return ""
}

func (m *Vdu) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *Vdu) GetDiskSize() string {
	if m != nil {
		return m.DiskSize
	}
	return ""
}

func (m *Vdu) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Vdu) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vdu) GetVnfcs() []*Vnfc {
	if m != nil {
		return m.Vnfcs
	}
	return nil
}

type VirtualLink struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsManagement         bool     `protobuf:"varint,2,opt,name=is_management,json=isManagement,proto3" json:"is_management,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtualLink) Reset()         { *m = VirtualLink{} }
func (m *VirtualLink) String() string { return proto.CompactTextString(m) }
func (*VirtualLink) ProtoMessage()    {}
func (*VirtualLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{1}
}

func (m *VirtualLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualLink.Unmarshal(m, b)
}
func (m *VirtualLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualLink.Marshal(b, m, deterministic)
}
func (m *VirtualLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualLink.Merge(m, src)
}
func (m *VirtualLink) XXX_Size() int {
	return xxx_messageInfo_VirtualLink.Size(m)
}
func (m *VirtualLink) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualLink.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualLink proto.InternalMessageInfo

func (m *VirtualLink) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualLink) GetIsManagement() bool {
	if m != nil {
		return m.IsManagement
	}
	return false
}

type VnfdPostTemplate struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vdus                 []*Vdu         `protobuf:"bytes,2,rep,name=vdus,proto3" json:"vdus,omitempty"`
	VirtualLinks         []*VirtualLink `protobuf:"bytes,3,rep,name=virtual_links,json=virtualLinks,proto3" json:"virtual_links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *VnfdPostTemplate) Reset()         { *m = VnfdPostTemplate{} }
func (m *VnfdPostTemplate) String() string { return proto.CompactTextString(m) }
func (*VnfdPostTemplate) ProtoMessage()    {}
func (*VnfdPostTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{2}
}

func (m *VnfdPostTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VnfdPostTemplate.Unmarshal(m, b)
}
func (m *VnfdPostTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VnfdPostTemplate.Marshal(b, m, deterministic)
}
func (m *VnfdPostTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VnfdPostTemplate.Merge(m, src)
}
func (m *VnfdPostTemplate) XXX_Size() int {
	return xxx_messageInfo_VnfdPostTemplate.Size(m)
}
func (m *VnfdPostTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_VnfdPostTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_VnfdPostTemplate proto.InternalMessageInfo

func (m *VnfdPostTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VnfdPostTemplate) GetVdus() []*Vdu {
	if m != nil {
		return m.Vdus
	}
	return nil
}

func (m *VnfdPostTemplate) GetVirtualLinks() []*VirtualLink {
	if m != nil {
		return m.VirtualLinks
	}
	return nil
}

type VnfdInstanceTemplate struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string               `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Vnfd                 *VnfdPostTemplate    `protobuf:"bytes,10,opt,name=vnfd,proto3" json:"vnfd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VnfdInstanceTemplate) Reset()         { *m = VnfdInstanceTemplate{} }
func (m *VnfdInstanceTemplate) String() string { return proto.CompactTextString(m) }
func (*VnfdInstanceTemplate) ProtoMessage()    {}
func (*VnfdInstanceTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{3}
}

func (m *VnfdInstanceTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VnfdInstanceTemplate.Unmarshal(m, b)
}
func (m *VnfdInstanceTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VnfdInstanceTemplate.Marshal(b, m, deterministic)
}
func (m *VnfdInstanceTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VnfdInstanceTemplate.Merge(m, src)
}
func (m *VnfdInstanceTemplate) XXX_Size() int {
	return xxx_messageInfo_VnfdInstanceTemplate.Size(m)
}
func (m *VnfdInstanceTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_VnfdInstanceTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_VnfdInstanceTemplate proto.InternalMessageInfo

func (m *VnfdInstanceTemplate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VnfdInstanceTemplate) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *VnfdInstanceTemplate) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *VnfdInstanceTemplate) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *VnfdInstanceTemplate) GetVnfd() *VnfdPostTemplate {
	if m != nil {
		return m.Vnfd
	}
	return nil
}

type PaginatedVnfdInstanceTemplate struct {
	Limit                uint32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalCount           uint32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	First                string                  `protobuf:"bytes,3,opt,name=first,proto3" json:"first,omitempty"`
	Next                 string                  `protobuf:"bytes,4,opt,name=next,proto3" json:"next,omitempty"`
	Vnfds                []*VnfdInstanceTemplate `protobuf:"bytes,5,rep,name=vnfds,proto3" json:"vnfds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PaginatedVnfdInstanceTemplate) Reset()         { *m = PaginatedVnfdInstanceTemplate{} }
func (m *PaginatedVnfdInstanceTemplate) String() string { return proto.CompactTextString(m) }
func (*PaginatedVnfdInstanceTemplate) ProtoMessage()    {}
func (*PaginatedVnfdInstanceTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{4}
}

func (m *PaginatedVnfdInstanceTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginatedVnfdInstanceTemplate.Unmarshal(m, b)
}
func (m *PaginatedVnfdInstanceTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginatedVnfdInstanceTemplate.Marshal(b, m, deterministic)
}
func (m *PaginatedVnfdInstanceTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginatedVnfdInstanceTemplate.Merge(m, src)
}
func (m *PaginatedVnfdInstanceTemplate) XXX_Size() int {
	return xxx_messageInfo_PaginatedVnfdInstanceTemplate.Size(m)
}
func (m *PaginatedVnfdInstanceTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginatedVnfdInstanceTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_PaginatedVnfdInstanceTemplate proto.InternalMessageInfo

func (m *PaginatedVnfdInstanceTemplate) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PaginatedVnfdInstanceTemplate) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *PaginatedVnfdInstanceTemplate) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *PaginatedVnfdInstanceTemplate) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

func (m *PaginatedVnfdInstanceTemplate) GetVnfds() []*VnfdInstanceTemplate {
	if m != nil {
		return m.Vnfds
	}
	return nil
}

type Vnfc struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ConnectionPoints     []*ConnectionPoint `protobuf:"bytes,2,rep,name=connection_points,json=connectionPoints,proto3" json:"connection_points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Vnfc) Reset()         { *m = Vnfc{} }
func (m *Vnfc) String() string { return proto.CompactTextString(m) }
func (*Vnfc) ProtoMessage()    {}
func (*Vnfc) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{5}
}

func (m *Vnfc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vnfc.Unmarshal(m, b)
}
func (m *Vnfc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vnfc.Marshal(b, m, deterministic)
}
func (m *Vnfc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vnfc.Merge(m, src)
}
func (m *Vnfc) XXX_Size() int {
	return xxx_messageInfo_Vnfc.Size(m)
}
func (m *Vnfc) XXX_DiscardUnknown() {
	xxx_messageInfo_Vnfc.DiscardUnknown(m)
}

var xxx_messageInfo_Vnfc proto.InternalMessageInfo

func (m *Vnfc) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vnfc) GetConnectionPoints() []*ConnectionPoint {
	if m != nil {
		return m.ConnectionPoints
	}
	return nil
}

type ConnectionPoint struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress            string   `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	VirtualLinkReference []string `protobuf:"bytes,3,rep,name=virtual_link_reference,json=virtualLinkReference,proto3" json:"virtual_link_reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionPoint) Reset()         { *m = ConnectionPoint{} }
func (m *ConnectionPoint) String() string { return proto.CompactTextString(m) }
func (*ConnectionPoint) ProtoMessage()    {}
func (*ConnectionPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{6}
}

func (m *ConnectionPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionPoint.Unmarshal(m, b)
}
func (m *ConnectionPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionPoint.Marshal(b, m, deterministic)
}
func (m *ConnectionPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionPoint.Merge(m, src)
}
func (m *ConnectionPoint) XXX_Size() int {
	return xxx_messageInfo_ConnectionPoint.Size(m)
}
func (m *ConnectionPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionPoint.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionPoint proto.InternalMessageInfo

func (m *ConnectionPoint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConnectionPoint) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *ConnectionPoint) GetVirtualLinkReference() []string {
	if m != nil {
		return m.VirtualLinkReference
	}
	return nil
}

type CreateRequest struct {
	Api                  string            `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Vnfd                 *VnfdPostTemplate `protobuf:"bytes,2,opt,name=vnfd,proto3" json:"vnfd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{7}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetVnfd() *VnfdPostTemplate {
	if m != nil {
		return m.Vnfd
	}
	return nil
}

type CreateResponse struct {
	Api                  string                `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Vnfd                 *VnfdInstanceTemplate `protobuf:"bytes,10,opt,name=vnfd,proto3" json:"vnfd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{8}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetVnfd() *VnfdInstanceTemplate {
	if m != nil {
		return m.Vnfd
	}
	return nil
}

type GetRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{9}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Api                  string                `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Vnfd                 *VnfdInstanceTemplate `protobuf:"bytes,2,opt,name=vnfd,proto3" json:"vnfd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{10}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetResponse) GetVnfd() *VnfdInstanceTemplate {
	if m != nil {
		return m.Vnfd
	}
	return nil
}

type ListRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{11}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type ListResponse struct {
	Api                  string                           `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	PaginatedVnfds       []*PaginatedVnfdInstanceTemplate `protobuf:"bytes,10,rep,name=paginated_vnfds,json=paginatedVnfds,proto3" json:"paginated_vnfds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{12}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ListResponse) GetPaginatedVnfds() []*PaginatedVnfdInstanceTemplate {
	if m != nil {
		return m.PaginatedVnfds
	}
	return nil
}

type DeleteRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{13}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_070c44c1219ffa9f, []int{14}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Vdu)(nil), "v1.Vdu")
	proto.RegisterType((*VirtualLink)(nil), "v1.VirtualLink")
	proto.RegisterType((*VnfdPostTemplate)(nil), "v1.VnfdPostTemplate")
	proto.RegisterType((*VnfdInstanceTemplate)(nil), "v1.VnfdInstanceTemplate")
	proto.RegisterType((*PaginatedVnfdInstanceTemplate)(nil), "v1.PaginatedVnfdInstanceTemplate")
	proto.RegisterType((*Vnfc)(nil), "v1.Vnfc")
	proto.RegisterType((*ConnectionPoint)(nil), "v1.ConnectionPoint")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
	proto.RegisterType((*GetRequest)(nil), "v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "v1.GetResponse")
	proto.RegisterType((*ListRequest)(nil), "v1.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "v1.ListResponse")
	proto.RegisterType((*DeleteRequest)(nil), "v1.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "v1.DeleteResponse")
}

func init() { proto.RegisterFile("vnfd.proto", fileDescriptor_070c44c1219ffa9f) }

var fileDescriptor_070c44c1219ffa9f = []byte{
	// 742 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6a, 0xdb, 0x48,
	0x14, 0xc6, 0xf2, 0xcf, 0xc6, 0xc7, 0xf1, 0x4f, 0x66, 0x4d, 0x10, 0x0e, 0xd9, 0x64, 0xb5, 0xb0,
	0x64, 0x61, 0x91, 0x49, 0x36, 0x37, 0x7b, 0xd7, 0x90, 0xd2, 0xd0, 0x36, 0x01, 0xa3, 0x04, 0x5f,
	0x15, 0xc4, 0x44, 0x1a, 0x9b, 0x21, 0xd2, 0x48, 0xd5, 0x8c, 0x44, 0x93, 0x47, 0xe9, 0x53, 0xf4,
	0x19, 0xfa, 0x20, 0x7d, 0x96, 0x32, 0x67, 0x24, 0xff, 0x04, 0x3b, 0xe9, 0x9d, 0xcf, 0x77, 0xfe,
	0xbe, 0x39, 0xdf, 0x27, 0x03, 0x14, 0x62, 0x16, 0xba, 0x69, 0x96, 0xa8, 0x84, 0x58, 0xc5, 0xe9,
	0xe8, 0x68, 0x9e, 0x24, 0xf3, 0x88, 0x8d, 0x11, 0xb9, 0xcf, 0x67, 0x63, 0xc5, 0x63, 0x26, 0x15,
	0x8d, 0x53, 0x53, 0xe4, 0x7c, 0xad, 0x41, 0x7d, 0x1a, 0xe6, 0x64, 0x08, 0xcd, 0x22, 0x48, 0x73,
	0x69, 0xd7, 0x8e, 0x6b, 0x27, 0x6d, 0xcf, 0x04, 0x64, 0x1f, 0x5a, 0x31, 0x8b, 0x93, 0xec, 0xd1,
	0xb6, 0x10, 0x2e, 0x23, 0x72, 0x00, 0xed, 0x90, 0xcb, 0x07, 0x5f, 0xf2, 0x27, 0x66, 0xd7, 0x31,
	0xb5, 0xa3, 0x81, 0x5b, 0xfe, 0xc4, 0xf4, 0x28, 0x1e, 0xd3, 0x39, 0xb3, 0x1b, 0x66, 0x14, 0x06,
	0x84, 0x40, 0x43, 0xd0, 0x98, 0xd9, 0x4d, 0x04, 0xf1, 0x37, 0xf9, 0x03, 0x9a, 0x85, 0x98, 0x05,
	0xd2, 0x6e, 0x1d, 0xd7, 0x4f, 0x3a, 0x67, 0x3b, 0x6e, 0x71, 0xea, 0x4e, 0xc5, 0x2c, 0xf0, 0x0c,
	0xec, 0xbc, 0x83, 0xce, 0x94, 0x67, 0x2a, 0xa7, 0xd1, 0x35, 0x17, 0x0f, 0x8b, 0x11, 0xb5, 0x95,
	0x11, 0x7f, 0x41, 0x97, 0x4b, 0x3f, 0xa6, 0x82, 0xce, 0x59, 0xcc, 0x84, 0x42, 0xa2, 0x3b, 0xde,
	0x2e, 0x97, 0x37, 0x0b, 0xcc, 0x79, 0x84, 0xc1, 0x54, 0xcc, 0xc2, 0x49, 0x22, 0xd5, 0x1d, 0x8b,
	0xd3, 0x88, 0x2a, 0xb6, 0x71, 0xd8, 0x01, 0x34, 0x8a, 0x30, 0x97, 0xb6, 0x85, 0x74, 0x7e, 0x43,
	0x3a, 0x61, 0xee, 0x21, 0x48, 0xce, 0xa1, 0x5b, 0x18, 0x32, 0x7e, 0xc4, 0xc5, 0x83, 0xb4, 0xeb,
	0x58, 0xd5, 0xc7, 0xaa, 0x25, 0x4b, 0x6f, 0xb7, 0x58, 0x06, 0xd2, 0xf9, 0x51, 0x83, 0xa1, 0xde,
	0xfd, 0x5e, 0x48, 0x45, 0x45, 0xc0, 0x16, 0xfb, 0x7b, 0x60, 0xf1, 0xb0, 0xdc, 0x6e, 0xf1, 0x50,
	0x9f, 0x5a, 0x2a, 0xaa, 0x70, 0x3b, 0x9e, 0xda, 0x44, 0xe4, 0x7f, 0x80, 0x20, 0x63, 0x54, 0xb1,
	0xd0, 0xa7, 0x0a, 0x6f, 0xdd, 0x39, 0x1b, 0xb9, 0x46, 0x56, 0xb7, 0x92, 0xd5, 0xbd, 0xab, 0x64,
	0xf5, 0xda, 0x65, 0xf5, 0x85, 0xd2, 0xad, 0x79, 0x1a, 0x56, 0xad, 0x8d, 0xd7, 0x5b, 0xcb, 0xea,
	0x0b, 0x45, 0x4e, 0xa0, 0xa1, 0x9d, 0x64, 0x03, 0x36, 0x0d, 0x4b, 0x61, 0xd6, 0x2e, 0xe8, 0x61,
	0x85, 0xf3, 0xad, 0x06, 0x87, 0x13, 0x3a, 0xe7, 0x42, 0x77, 0x6e, 0x7c, 0xe9, 0x10, 0x9a, 0x11,
	0x8f, 0xb9, 0xc2, 0xc7, 0x76, 0x3d, 0x13, 0x90, 0x23, 0xe8, 0xa8, 0x44, 0xd1, 0xc8, 0x0f, 0x92,
	0xbc, 0x94, 0xad, 0xeb, 0x01, 0x42, 0x97, 0x1a, 0xd1, 0x6d, 0x33, 0x9e, 0x49, 0x55, 0xfa, 0xcb,
	0x04, 0x28, 0x1b, 0xfb, 0xa2, 0x4a, 0x6f, 0xe1, 0x6f, 0xe2, 0xa2, 0x8d, 0x42, 0x69, 0x37, 0x51,
	0x11, 0xbb, 0x62, 0xfb, 0x9c, 0x89, 0x67, 0xca, 0x9c, 0x4f, 0xd0, 0xd0, 0x2e, 0xdb, 0x68, 0x81,
	0x37, 0xb0, 0x17, 0x24, 0x42, 0xb0, 0x40, 0xf1, 0x44, 0xf8, 0x69, 0xc2, 0x85, 0xaa, 0xfc, 0xf0,
	0xbb, 0x9e, 0x7b, 0xb9, 0x48, 0x4e, 0x74, 0xce, 0x1b, 0x04, 0xeb, 0x80, 0x74, 0x9e, 0xa0, 0xff,
	0xac, 0x68, 0xe3, 0xa2, 0x43, 0x00, 0x9e, 0xfa, 0x34, 0x0c, 0x33, 0x26, 0x2b, 0xcd, 0xdb, 0x3c,
	0xbd, 0x30, 0x00, 0x39, 0x87, 0xfd, 0x55, 0xb7, 0xf9, 0x19, 0x9b, 0xb1, 0x8c, 0x89, 0x80, 0xa1,
	0xed, 0xda, 0xde, 0x70, 0xc5, 0x65, 0x5e, 0x95, 0x73, 0x3e, 0x42, 0xf7, 0x12, 0xe5, 0xf7, 0xd8,
	0xe7, 0x9c, 0x49, 0x45, 0x06, 0x50, 0xa7, 0x29, 0x2f, 0x17, 0xeb, 0x9f, 0x0b, 0x65, 0xad, 0x57,
	0x95, 0x9d, 0x40, 0xaf, 0x1a, 0x26, 0xd3, 0x44, 0x48, 0xb6, 0x61, 0xda, 0xbf, 0x6b, 0x3e, 0xd9,
	0x7e, 0x79, 0x33, 0xd1, 0x05, 0xb8, 0x62, 0x6a, 0x3b, 0x37, 0xf3, 0x4d, 0x58, 0xd5, 0x37, 0xe1,
	0xdc, 0x40, 0x07, 0xeb, 0x5f, 0x5d, 0x6f, 0xfd, 0xd2, 0xfa, 0x23, 0xe8, 0x5c, 0x73, 0xb9, 0x7d,
	0xbf, 0x13, 0xc1, 0xae, 0x29, 0xd8, 0xba, 0xf0, 0x03, 0xf4, 0xd3, 0xca, 0xec, 0xbe, 0x31, 0x1d,
	0xa0, 0x39, 0xfe, 0xd4, 0xbb, 0x5f, 0xfc, 0x0e, 0xbc, 0x5e, 0xba, 0x9a, 0x96, 0xce, 0x29, 0x74,
	0xdf, 0xb2, 0x88, 0xbd, 0x24, 0xd6, 0xf3, 0x83, 0x0c, 0xa0, 0x57, 0xb5, 0x18, 0x8a, 0x67, 0xdf,
	0x6b, 0xd0, 0xd1, 0xe3, 0x6e, 0x59, 0x56, 0xf0, 0x80, 0x91, 0x31, 0xb4, 0x8c, 0x68, 0x64, 0x0f,
	0xed, 0xba, 0xea, 0x86, 0x11, 0x59, 0x85, 0xca, 0x37, 0xfe, 0x0d, 0xf5, 0x2b, 0xa6, 0x48, 0x4f,
	0xa7, 0x96, 0xe2, 0x8c, 0xfa, 0x8b, 0xb8, 0xac, 0xfb, 0x07, 0x1a, 0xfa, 0x36, 0x04, 0x13, 0x2b,
	0x67, 0x1c, 0x0d, 0x96, 0x40, 0x59, 0x3a, 0x86, 0x96, 0x61, 0x69, 0x38, 0xac, 0x3d, 0xd2, 0x70,
	0x58, 0x7f, 0xc4, 0x7d, 0x0b, 0xff, 0x8c, 0xfe, 0xfb, 0x19, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x7e,
	0x88, 0x93, 0xbe, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VnfdServiceClient is the client API for VnfdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VnfdServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type vnfdServiceClient struct {
	cc *grpc.ClientConn
}

func NewVnfdServiceClient(cc *grpc.ClientConn) VnfdServiceClient {
	return &vnfdServiceClient{cc}
}

func (c *vnfdServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/v1.VnfdService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vnfdServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/v1.VnfdService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vnfdServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/v1.VnfdService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vnfdServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/v1.VnfdService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VnfdServiceServer is the server API for VnfdService service.
type VnfdServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterVnfdServiceServer(s *grpc.Server, srv VnfdServiceServer) {
	s.RegisterService(&_VnfdService_serviceDesc, srv)
}

func _VnfdService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VnfdServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VnfdService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VnfdServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VnfdService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VnfdServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VnfdService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VnfdServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VnfdService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VnfdServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VnfdService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VnfdServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VnfdService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VnfdServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VnfdService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VnfdServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VnfdService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VnfdService",
	HandlerType: (*VnfdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _VnfdService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _VnfdService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _VnfdService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VnfdService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vnfd.proto",
}
